name: Deployment
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v4
      - name: Install deps
        run: yarn
      - name: Lint code
        run: yarn lint
      - name: Build app
        run: yarn build
      - name: Deploy
        run: echo deploying...